/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@renderer/layouts/base-layout/index.vue";
import BlankLayout from "@renderer/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  "detail-page_actress": () => import("@renderer/views/_constants/detail-page/actress/index.vue"),
  "detail-page_category": () => import("@renderer/views/_constants/detail-page/category/index.vue"),
  "detail-page_video-list": () => import("@renderer/views/_constants/detail-page/video-list/index.vue"),
  "detail-page_video": () => import("@renderer/views/_constants/detail-page/video/index.vue"),
  setting: () => import("@renderer/views/_constants/setting/index.vue"),
  403: () => import("@renderer/views/_error/403/index.vue"),
  404: () => import("@renderer/views/_error/404/index.vue"),
  500: () => import("@renderer/views/_error/500/index.vue"),
  category_actress: () => import("@renderer/views/category/actress/index.vue"),
  category_series: () => import("@renderer/views/category/series/index.vue"),
  category_studio: () => import("@renderer/views/category/studio/index.vue"),
  favorites: () => import("@renderer/views/favorites/index.vue"),
  home: () => import("@renderer/views/home/index.vue"),
  library: () => import("@renderer/views/library/index.vue"),
  login: () => import("@renderer/views/login/index.vue"),
};
